mindmap
  root((TEREP))
    Domborzat
      síkság
      domb
      hegy
    Vizek
      folyók
      tavak
      mocsarak
    Növényzet
      erdők
      bokros területek
      mezők
    Talaj
      homok
      agyag
      szikla
    Közlekedési hálózat
      utak
      vasutak
      hidak
    Települések
      városok
      falvak
      ipari létesítmények
